-- MySQL Script generated by MySQL Workbench
-- Thu Mar 29 11:08:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema som2_demo
-- -----------------------------------------------------
-- 演示数据库
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `contact_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contact_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `contact_user` (
  `cid` BIGINT NOT NULL AUTO_INCREMENT,
  `uid` BIGINT NOT NULL,
  `c_name` VARCHAR(45) NOT NULL,
  `c_sex` VARCHAR(5) NOT NULL,
  `c_tel` VARCHAR(20) NOT NULL,
  `c_email` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cid`)
  )engine=InnoDB
  default character set=utf8
  collate=utf8_bin;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
