-- MySQL Script generated by MySQL Workbench
-- Mon Apr  2 10:16:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `contact_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contact_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `contact_user` (
  `cid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `uid` BIGINT(20) NOT NULL,
  `c_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `c_sex` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `c_tel` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `c_email` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`cid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `order_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order_contact` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `order_contact` (
  `order_contact_user_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `oid` BIGINT(20) NOT NULL,
  `cid` BIGINT(20) NOT NULL,
  PRIMARY KEY (`order_contact_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `order_rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order_rooms` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `order_rooms` (
  `order_rooms_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `oid` BIGINT(20) NOT NULL,
  `rid` BIGINT(20) NOT NULL,
  PRIMARY KEY (`order_rooms_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orders` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `orders` (
  `oid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `uid` BIGINT(20) NOT NULL COMMENT '用户id',
  `room_id` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '房间号',
  `total_num` INT(11) NOT NULL COMMENT '房间电话号码',
  `account` DECIMAL(10,4) NOT NULL DEFAULT '0.0000' COMMENT '订单金额',
  `in_time` DATETIME NOT NULL COMMENT '入住时间',
  `out_time` DATETIME NOT NULL COMMENT '退房时间',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`oid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rooms` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rooms` (
  `rid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `room_id` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `romm_type` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `room_state` CHAR(2) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `room_tel` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `room_loc` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `remark` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`rid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user` (
  `uid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `password` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `real_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '真实姓名',
  `sex` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '性别',
  `tel_num` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '电话号码',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;
CREATE UNIQUE INDEX `username_UNIQUE` ON `user` (`username` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
