-- MySQL Script generated by MySQL Workbench
-- Tue Apr  3 10:08:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `contactuser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contactuser` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `contactuser` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '用户联系人id\n',
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '联系人姓名',
  `sex` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '联系人性别',
  `tele` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '联系人电话',
  `email` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '联系人邮箱',
  `create_time` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP(3) NULL DEFAULT  CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '联系人表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `order_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order_contact` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `order_contact` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '用户联系人id',
  `order_id` BIGINT(20) NOT NULL COMMENT '订单id',
  `contactuser_id` BIGINT(20) NOT NULL COMMENT '联系人id',
  `create_time` TIMESTAMP(3) NULL DEFAULT  CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP(3) NULL DEFAULT  CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '订单联系人表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `orderrooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orderrooms` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `orderrooms` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '订单房间表\n',
  `order_id` BIGINT(20) NOT NULL COMMENT '订单id',
  `room_id` BIGINT(20) NOT NULL COMMENT '房间id',
  `create_time` TIMESTAMP(3) NULL DEFAULT  CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP(3) NULL DEFAULT  CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '订单房间表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orders` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `orders` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `room_id` BIGINT(20) NOT NULL COMMENT '房间号',
  `total_num` INT(11) NOT NULL COMMENT '总人数',
  `account` DECIMAL(10,4) NOT NULL DEFAULT '0.0000' COMMENT '订单金额',
  `in_time` DATETIME NOT NULL COMMENT '入住时间',
  `out_time` DATETIME NOT NULL COMMENT '退房时间',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '订单表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rooms` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rooms` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '房间id',
  `number` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '房间号',
  `type` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '房间类型',
  `state` CHAR(2) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '房间状态',
  `tele` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '房间电话',
  `location` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '房间位置',
  `remark` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL COMMENT '房间其它信息备注',
  `create_time` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '房间表';

SHOW WARNINGS;
CREATE UNIQUE INDEX `createtime_UNIQUE` ON `rooms` (`create_time` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '用户表',
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `password` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `real_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '真实姓名',
  `sex` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '性别',
  `tele_number` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '电话号码',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '用户表';

SHOW WARNINGS;
CREATE UNIQUE INDEX `username_UNIQUE` ON `user` (`name` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
