-- MySQL Script generated by MySQL Workbench
-- Thu Mar 29 11:20:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema som2_demo
-- -----------------------------------------------------
-- 演示数据库
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `order_rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order_rooms` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `order_rooms` (
  `order_rooms_id` BIGINT NOT NULL AUTO_INCREMENT,
  `oid` BIGINT NOT NULL,
  `rid` BIGINT NOT NULL,
  PRIMARY KEY (`order_rooms_id`)
  )engine=InnoDB
  default character set=utf8
  collate=utf8_bin
  ;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
